### PR TITLE
This is my new enclosures contribution

### PR DESCRIPTION
**Pull request by Prius1954**

### CODE REVIEW

**Review by oscgonfer — APPROVED** [review]
Hi @Prius1954 

Thanks for the amazing work! I am merging the request now.

On a side note, do you think the hole in the back (for the hook) could be blind? This way if exposed in outdoor conditions it wouldn't leak water in.

Thanks again! ❤️

**Comment by oscgonfer** [comment]
Before merging, could you rename the folders and maybe put them in the outdoor enclosures?

Thanks

**Comment by Prius1954** [comment]
Hi Oscar

The blind hole is indeed a very good idea!!

Will do and come back.

Best

Andreas Manz

**Comment by Prius1954** [comment]
Yes, I’ll also do this.

Kind regards

Andreas Manz

**Comment by oscgonfer** [comment]
Hi @Prius1954,

How is this going?

**Pull request merged**
